models:
  - name: stg_retail
    description: "Staging retail — données nettoyées et typées"
    columns:
      - name: transaction_id
        description: "Identifiant unique de transaction"
        tests:
          - unique
          - not_null
      - name: montant_total
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0
              max_value: 10000
      - name: categorie_produit
        tests:
          - not_null
          - accepted_values:
              values: ['Beauty', 'Clothing', 'Electronics']